# Generated by Django 3.2.6 on 2021-08-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='mycv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
