# Generated by Django 3.2.6 on 2021-08-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20210821_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description',
        ),
        migrations.AddField(
            model_name='about',
            name='description1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description2',
            field=models.TextField(null=True),
        ),
    ]
