# Generated by Django 3.2.6 on 2021-08-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_alter_projects_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='skill',
            field=models.TextField(blank=True, max_length=230, null=True),
        ),
    ]
