# Generated by Django 3.2.6 on 2021-11-28 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_delete_skillshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skilla',
            new_name='skill',
        ),
    ]
