# Generated by Django 3.2.6 on 2021-12-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_rename_skilla_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
