# Generated by Django 3.2.6 on 2021-12-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_auto_20211214_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
