# Generated by Django 3.2.6 on 2021-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_alter_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
